### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by mehdizarei** [ShrewdSpirit/credman#1]
Can you do something about its recovery issue? it's a valuable app and i think it would be good enough  with that option to be operational.

**Comment by mehdizarei** [comment]
Of course it's operational right now, but i think the recovery option is very useful.

**Comment by ShrewdSpirit** [comment]
Since the AES algorithm is used for encryption, it's not possible to recover/reset the password unless you start bruteforcing the encrypted content.

**Comment by mehdizarei** [comment]
It's just exactly **one password** we must remember, isn't it?
I think i can do it.

**Comment by ShrewdSpirit** [comment]
Figured out a way for this. Will be implemented.
